### ISSUE TITLE
Output Issues

### ISSUE THREAD

**Issue by typkrft** [rieck/perplex#1]
Is there a way to just rename the files where they are instead of putting them a separate output directory? I have several TBs of files split between hard drives and no single output folder is going to hold everything. 

Thanks

**Comment by typkrft** [comment]
Sorry I realized after looking at the actual code I just needed to point it to correct directory. 

Another question....

Is there a way to just rename the files where they are instead of putting them a separate output directory? I have several TBs of files split between hard drives and no single output folder is going to hold everything. 

Thanks again

**Comment by rieck** [comment]
This should be possible. Note, however, that you may damage your library if something goes wrong with the renaming process. The corresponding code is in the `copy_rename` function.
