### ISSUE TITLE
Does not work with non-ascii characters in filenames

### ISSUE THREAD

**Issue by skriker** [rieck/perplex#3]
Unfortunately it seems that this script cannot handle non-ascii characters in filenames - in original name as well as in the new name.

Alway get similar messages to: "UnicodeEncodeError: 'ascii' codec can't encode character u'\u010d' in position 22: ordinal not in range(128)"

**Comment by rieck** [comment]
That's strange. Can you paste the entire stack trace? Regards, Konrad
