### ISSUE TITLE
manual/special input directory?

### ISSUE THREAD

**Issue by snickers2k** [rieck/perplex#4]
hey.
this tool is really awesome. just what i looked for.
but my problem is, i plan to only rename a "unsorted"-directory, not matched by filebot. so this can be matched/reviewed inside plex and then let it move by perplex.
is this possible?

thank you

**Comment by rieck** [comment]
I am not sure what you want to achieve. What is `filebot`? Are you referring to the media agents of Plex?

The tool `perplex` will read the internal database of Plex and rename files according to the movie titles in this database. So, you can import and review files inside Plex and then rename them.

Regards, Konrad
