### ISSUE TITLE
Is this sill working?

### ISSUE THREAD

**Issue by rikibez** [rieck/perplex#6]
I've just tried it and I've got this error:

> Analyzing Plex database:
> Traceback (most recent call last):
>   File "./perplex.py", line 125, in <module>
>     movies = build_db(args.plex)
>   File "./perplex.py", line 34, in build_db
>     db = sqlite3.connect(dbfile)
> ValueError: database parameter must be string or APSW Connection object

So I guess if is this project still in place or not working with latest Plex DBs.

Thanks

**Comment by rikibez** [comment]
Thanks for your reply.

I'm using Plex with docker and I suppose the issue would be the path
"plex_dir" but I haven't found where is declared into your code.

I found the db here, with a lot more dbs:



















***@***.***:/opt/plex/Library/Application Support/Plex Media
Server/Plug-in Support/Databases$ ls -lhtotal 332M-rw-r--r-- 1 anatra
anatra 356K May  4 11:13 com.plexapp.plugins.library.blobs.db-rw-r--r-- 1
anatra anatra 3.9M Apr 29 02:03
com.plexapp.plugins.library.blobs.db-2022-04-29-rw-r--r-- 1 anatra anatra
356K May  2 02:03 com.plexapp.plugins.library.blobs.db-2022-05-02-rw-r--r--
1 anatra anatra 356K May  5 02:04
com.plexapp.plugins.library.blobs.db-2022-05-05-rw-r--r-- 1 anatra anatra
356K May  8 02:04 com.plexapp.plugins.library.blobs.db-2022-05-08-rw-r--r--
1 anatra anatra  32K May  6 02:03
com.plexapp.plugins.library.blobs.db-shm-rw-r--r-- 1 anatra anatra 366K May
 6 02:03 com.plexapp.plugins.library.blobs.db-wal-rw-r--r-- 1 anatra anatra
 57M May  9 13:15 com.plexapp.plugins.library.db-rw-r--r-- 1 anatra anatra
 55M Apr 29 02:03 com.plexapp.plugins.library.db-2022-04-29-rw-r--r-- 1
anatra anatra  50M May  2 02:03
com.plexapp.plugins.library.db-2022-05-02-rw-r--r-- 1 anatra anatra  52M
May  5 02:04 com.plexapp.plugins.library.db-2022-05-05-rw-r--r-- 1 anatra
anatra  57M May  8 02:04
com.plexapp.plugins.library.db-2022-05-08-rw-r--r-- 1 anatra anatra 416K
May  9 13:20 com.plexapp.plugins.library.db-shm-rw-r--r-- 1 anatra anatra
 53M May  9 13:20 com.plexapp.plugins.library.db-wal-rw-r--r-- 1 anatra
anatra 276K May  4 11:13 com.plexapp.plugins.trakttv.db-rw-r--r-- 1 anatra
anatra  32K May  9 03:00 com.plexapp.plugins.trakttv.db-shm-rw-r--r-- 1
anatra anatra 4.0M May  9 03:00
***@***.***:/opt/plex/Library/Application
Support/Plex Media Server/Plug-in Support/Databases$*

Regards,
Riccardo

Il giorno lun 9 mag 2022 alle ore 10:06 Konrad Rieck <
***@***.***> ha scritto:

**Comment by rieck** [comment]
Okay, let me try to give some tips (Disclaimer: I haven't looked at Plex for years!)

1. I assume that one of the database files in your directory is the correct one. You could try adding a movie and see if the timestamp changes in the listing.

2. If you found the right file, you can copy (not move) it to another directory and point my tool to this directory. Maybe you will have luck then.

Best regards,
Konrad

**Comment by rikibez** [comment]
I'm sorry Konrad. I didn't reply to you.

I checked what you suggested and now I have another problem









*Loading metadata from movies.dbTraceback (most recent call last):  File
"./perplex.py", line 129, in <module>    movies =
json.load(gzip.open(args.load))  File "/usr/lib/python2.7/gzip.py", line
34, in open    return GzipFile(filename, mode, compresslevel)  File
"/usr/lib/python2.7/gzip.py", line 94, in __init__    fileobj =
self.myfileobj = __builtin__.open(filename, mode or 'rb')IOError: [Errno 2]
No such file or directory: 'movies.db'*

I used this command: ./perplex.py --load movies.db --dest /mnt/remote/test
--dry

Thanks
Riccardo

Il giorno lun 9 mag 2022 alle ore 13:30 Konrad Rieck <
***@***.***> ha scritto:
