### ISSUE TITLE
Not working...

### ISSUE THREAD

**Issue by vdias** [rieck/perplex#7]
./perplex.py --save movies.db --plex /var/plex

  _File "/scripts/./perplex.py", line 32
    print "Analyzing Plex database:",
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Analyzing Plex database:", end=" ")?_

**Comment by mlsec-crawl** [comment]
The script is old and uses Python 2. You are likely running it with Python 3. Let me see if I can fix this directly. 

Best regards, Konrad

**Comment by rieck** [comment]
Hopefully fixed with #8
