### ISSUE TITLE
Feature Request imdb added to folder name

### ISSUE THREAD

**Issue by Dracon09** [rieck/perplex#9]
Hi,

Any chance in the rename you could add the imbd to the folder name as noted in the plex naming documentation? I try to leave the actual movie file name alone so I know the source and quality.

https://support.plex.tv/articles/naming-and-organizing-your-movie-media-files/

Example:
/Movies
   /Batman Begins (2005) {imdb-tt0372784}
      Batman.Begins.2005.REMASTERED.1080p.BluRay.H264.AAC-RARBG.mp4

Thanks

**Comment by rieck** [comment]
Thanks for the idea. Do you know whether this information is present in the Plex database? Best regards.

**Comment by Dracon09** [comment]
a google search gave me this answer

you can get IMDB, TVDB and TMDB ID's from this call:
/library/metadata/(plexMovieID)
Look in MediaContainer.Video[0].Guid

sourece; https://www.reddit.com/r/PleX/comments/stznke/imdb_id_in_the_plex_database/

**Comment by Dracon09** [comment]
I found another way to do this by taking the file name "Batman.Begins.2005.REMASTERED.1080p.BluRay.H264.AAC-RARBG" and sending it to the python RarbgAPI. This will return the IMDB ID.

**Comment by Dracon09** [comment]
I ended up writing a Python script that takes the movie name an looks up the IMDB and re-names the folder. You can close this feature request. Thanks
